id: IC1DA4A09
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T18:31:31+00:00'
last_modified: '2022-06-07T21:19:08.001738+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20577
  title: བོད་ཀྱི་གཏན་ཚིགས་རིག་པའི་སྤྱི་དོན་གོ་བདེར་བརྗོད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    DEAB:
      image_group_id: I1KG10160
      title: ''
      total_pages: 266
      order: 1
      base_file: DEAB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
